<a href="https://colab.research.google.com/github/ishammansoor/Pytorch_Fundamentals/blob/main/PyTorch_Fundamental_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTroch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plit

## Introduction to Tensors

### Creating tensors

In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector

vector = torch.tensor([7, 7])

In [9]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim


2

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX.shape


torch.Size([2, 2])

In [21]:
TENSOR = torch.tensor([[[1,2,3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.ndim


3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])